version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_service
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:
