FROM postgres:latest

# Kopier init-fil
COPY init.sql /docker-entrypoint-initdb.d/

# Kopier konfigurationsfiler
COPY postgresql.conf /etc/postgresql/postgresql.conf
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
